version: '3.1'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./data/formassist:/opt/static/formassist
    networks:
      - formassist_net

  formassist:
    build:
      context: ./formassist
    volumes:
      - ./data/formassist/:/app/formassist/output
    networks:
      - formassist_net

  fess01:
    build:
      context: ./fess01
    container_name: fess01
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - es01
    environment:
      - RUN_ELASTICSEARCH=false
      - "ES_HTTP_URL=http://es01:9200"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary/"
    networks:
      - formassist_net
    volumes:
      - ./data/fess/opt/fess:/opt/fess
      - ./data/fess/var/lib/fess:/var/lib/fess
      - ./data/fess/var/log/fess:/var/log/fess

  es01:
    image: codelibs/fess-elasticsearch:7.4.2
    container_name: es01
    restart: always
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=fess-es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "FESS_DICTIONARY_PATH=/usr/share/elasticsearch/config/dictionary"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/usr/share/elasticsearch/config/dictionary:/usr/share/elasticsearch/config/dictionary
    ports:
      - 9200:9200
    networks:
      - formassist_net

networks:
  formassist_net:
    driver: bridge
